katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import delete_task, register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import show_todolist
from todolist.views import create_task
from todolist.views import update
from todolist.views import delete
from todolist.views import return_data_JSON
from todolist.views import add_task
from todolist.views import delete_task

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('update/<update_id>', update, name='update'),
    path('delete/<delete_id>', delete_task, name='delete_task'),
    path('json/', return_data_JSON, name='return_data_JSON'),
    path('add/', add_task, name='add_task'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField()
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms

class CreateTask(forms.Form):
    title = forms.CharField(label='Title')
    description = forms.CharField(label='Description')

todolist/views.py
import datetime
import imp
from todolist.models import Task
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from todolist.forms import CreateTask
from django.http import HttpResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    username = None
    if request.user.is_authenticated:
        username = request.user.get_username()

    # data_task = Task.objects.filter(user=request.user)

    context = {
        'username': username,
        # 'list_task': data_task,
        'user': request.user,
        'last_login': request.COOKIES['last_login']
    }

    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def create_task(request):
    form = CreateTask()

    if request.method == 'POST':
        form = CreateTask(request.POST)
        if form.is_valid():
            date = datetime.datetime.now()
            title = request.POST.get('title')
            description = request.POST.get('description')
            user = request.user
            task = Task(user=user, date=date, title = title, description = description)
            task.save()
            return redirect('todolist:show_todolist')

    username = None
    if request.user.is_authenticated:
        username = request.user.get_username()

    context = {
        'form':form,
        'username': username
    }
    return render(request, "create_task.html", context)

@login_required(login_url='/todolist/login/')
def update(request, update_id):
    task_update = Task.objects.get(id=update_id)

    if task_update.is_finished == False:
        task_update.is_finished = True
    else:
        task_update.is_finished = False

    task_update.save()

    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def delete(request, delete_id):
    Task.objects.filter(id=delete_id).delete()
    return redirect('todolist:show_todolist')

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def return_data_JSON(request):
    data = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
@csrf_exempt
def add_task(request):
    if request.method == 'POST':
        date = datetime.datetime.now()
        title = request.POST.get('title')
        description = request.POST.get('description')
        user = request.user
        task = Task(user=user, date=date, title = title, description = description)
        task.save()

        output = {
            'pk':task.pk,
            'fields':{
                'title':task.title,
                'description':task.description,
                'is_finished':task.is_finished,
                'date':task.date,
            }
        }

        return JsonResponse(output)

@login_required(login_url='/todolist/login/')
@csrf_exempt
def delete_task(request, delete_id):
    if (request.method == 'DELETE'):
        Task.objects.filter(id=delete_id).delete()

        return HttpResponse(status=202)

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create New Task</title>
{% endblock meta %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid navbar-dark bg-dark">
        <a class="navbar-brand navbar-dark bg-dark">{{username}}</a>
        <button class="navbar-toggler navbar-dark bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon navbar-dark bg-dark"></span>
          </button>
          <div class="collapse navbar-collapse navbar-dark bg-dark" id="navbarSupportedContent">
              <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link navbar-dark bg-dark" href="{% url 'todolist:show_todolist' %}">Todolist<span class="sr-only navbar-dark bg-dark"></span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link navbar-dark bg-dark" href="{% url 'todolist:logout' %}">Logout</a>
                </li>
              </ul>
          </div>
    </div>
  </nav>

  <h1 class="text-zinc-800" style="font-weight:bold ; font-size:50px; text-align: center; margin-bottom: 20px;">Create New Task</h1>

<div class="items-center md:flex flex justify-center md:w-full">
  <form class="md:w-70 bg-zinc-800 shadow-md rounded px-8 pt-6 pb-8 mb-4" method="POST">
      {% csrf_token %}
      <div class="mb-4">
          <label class="block text-white text-sm font-bold mb-2" for="username">
              Title
      </label>
      <label class="text-lg bg-white shadow appearance-none border rounded w-full py-2 px-3 text-zinc-800 leading-tight focus:outline-none focus:shadow-outline">{{form.title}}</label>
  </div>
  <div class="mb-6">
      <label class="block text-white text-sm font-bold mb-2" for="description">
          Description
      </label>
      <label class="text-lg bg-white shadow appearance-none border rounded w-full py-2 px-3 text-zinc-800 leading-tight focus:outline-none focus:shadow-outline">{{form.description}}</label>
  </div>
    <div class="flex items-center justify-center">
      <input class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"  type="submit" value="Submit">
  </div>
</form>
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid navbar-dark bg-dark">
        <a class="navbar-brand navbar-dark bg-dark">Welcome!</a>
        <button class="navbar-toggler navbar-dark bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon navbar-dark bg-dark"></span>
          </button>
          <div class="collapse navbar-collapse navbar-dark bg-dark" id="navbarSupportedContent">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link navbar-dark bg-dark" href="{% url 'todolist:register' %}">Belum mempunyai akun?<span class="sr-only navbar-dark bg-dark"></span></a>
                </li>
              </ul>
          </div>
    </div>
  </nav>

  <h1 class="text-zinc-800" style="font-weight:bold ; font-size:50px; text-align: center; margin-bottom: 20px;">Login</h1>


<div class="items-center md:flex flex justify-center">
    <form class="bg-zinc-800 shadow-md rounded px-8 pt-6 pb-8 mb-4" method="POST">
        {% csrf_token %}
        <div class="mb-4">
            <label class="block text-white text-sm font-bold mb-2" for="username">
                Username
        </label>
        <input class="shadow appearance-none border rounded w-full py-2 px-3 text-zinc-800 leading-tight focus:outline-none focus:shadow-outline" type="text" name="username" placeholder="Username">
    </div>
    <div class="mb-6">
        <label class="block text-white text-sm font-bold mb-2" for="password">
            Password
        </label>
        <input class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-zinc-800 mb-3 leading-tight focus:outline-none focus:shadow-outline" type="password" name="password" placeholder="Password">
        <p class="text-red-500 text-xs italic">Please choose a password.</p>
    </div>
      <div class="flex items-center justify-center">
        <input class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" value="Login">
    </div>
    {% if messages %}
        <ul style="margin-top: 5px;" class="text-white">
            {% for message in messages %}
                <li align="center">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</form>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid navbar-dark bg-dark">
        <a class="navbar-brand navbar-dark bg-dark">Welcome!</a>
        <button class="navbar-toggler navbar-dark bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon navbar-dark bg-dark"></span>
          </button>
          <div class="collapse navbar-collapse navbar-dark bg-dark" id="navbarSupportedContent">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link navbar-dark bg-dark" href="{% url 'todolist:login' %}">Login<span class="sr-only navbar-dark bg-dark"></span></a>
                </li>
              </ul>
          </div>
    </div>
  </nav>

  <h1 class="text-zinc-800" style="font-weight:bold ; font-size:50px; text-align: center; margin-bottom: 20px;">Formulir Registrasi</h1>  

<div class="items-center md:flex flex justify-center">
    <form class="bg-zinc-800 shadow-md rounded px-8 pt-6 pb-8 mb-4" method="POST">
        {% csrf_token %}
        <div class="mb-4">
            <label class="block text-white text-sm font-bold mb-2" for="username">
                Username
        </label>
        <label class="bg-white shadow appearance-none border rounded w-full py-2 px-3 text-zinc-800 leading-tight focus:outline-none focus:shadow-outline">{{form.username}}</label>
    </div>
    <div class="mb-6">
        <label class="block text-white text-sm font-bold mb-2" for="password">
            Password
        </label>
        <label class="bg-white shadow appearance-none border rounded w-full py-2 px-3 text-zinc-800 leading-tight focus:outline-none focus:shadow-outline">{{form.password1}}</label>
    </div>
    <div class="mb-6">
        <label class="block text-white text-sm font-bold mb-2" for="password">
            Password confirmation
        </label>
        <label class="bg-white shadow appearance-none border rounded w-full py-2 px-3 text-zinc-800 leading-tight focus:outline-none focus:shadow-outline">{{form.password2}}</label>
    </div>
      <div class="flex items-center justify-center">
        <input class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" name="submit" value="Daftar">
    </div>
    {% if messages %}
        <ul style="margin-top: 5px;" class="text-white">
            {% for message in messages %}
                <li align="center">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</form>
</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script>
    $(document).ready(function(){
      $.get('/todolist/json', function(data){
        for (i = 0; i < data.length; i++){
          var card = `<div id="${data[i].pk}--task" class="card text-white bg-dark mb-3 transform transition duration-500 hover:scale-105 flex-auto" style="max-width: 17rem; min-width: 17rem;">
          <div class="card-header text-white bg-dark mb-3"> ${data[i].fields.is_finished ? `Selesai`:`Belum Selesai`}
          <div class="card-body text-white bg-dark mb-3">
            <h4 class="card-title text-white bg-dark mb-3" style="text-align: center;">${data[i].fields.title}</h4>
            <p class="card-text text-white bg-dark mb-3" style="text-align: center;">${data[i].fields.description}</p>
            <div class="container text-white bg-dark mb-3" style="text-align: center;">
                <a><button class="button-update bg-green-600" style="margin-right: 20px; width: 75px; height: 30px;"><a class="font-update" href="/todolist/update/${data[i].pk}">Update</a></button></a>
                <a><button class="button-delete bg-red-600"style="width: 75px; height: 30px" ><a class="font-delete" onclick="deleteTask(${data[i].pk})">Delete</a></button></a>
            </div>
            <h6 class="card-title text-white bg-dark mb-3" style="text-align: center;">${data[i].fields.date}</h6>
          </div>
          </div>
          </div>`
          $('#todolist').append(card); 
        }
      });

      $('#add-task').click(function(){
        if ($('#title').val() && $('#description').val()){
          $.post('/todolist/add/', {title: $('#title').val(), description: $('#description').val()}, function(response, status){
            if (status == 'success'){
              var card = `<div id="${response.pk}--task" class="card text-white bg-dark mb-3 transform transition duration-500 hover:scale-105 flex-auto" style="max-width: 17rem; min-width: 17rem;">
              <div class="card-header text-white bg-dark mb-3"> ${response.fields.is_finished ? `Selesai`:`Belum Selesai`}
              <div class="card-body text-white bg-dark mb-3">
              <h4 class="card-title text-white bg-dark mb-3" style="text-align: center;">${response.fields.title}</h4>
              <p class="card-text text-white bg-dark mb-3" style="text-align: center;">${response.fields.description}</p>
              <div class="container text-white bg-dark mb-3" style="text-align: center;">
                <a><button class="button-update bg-green-600" style="margin-right: 20px; width: 75px; height: 30px;"><a class="font-update" href="/todolist/update/${response.pk}">Update</a></button></a>
                <a><button class="button-delete bg-red-600"style="width: 75px; height: 30px" ><a class="font-delete" onclick="deleteTask(${response.pk})">Delete</a></button></a>
              </div>
              <h6 class="card-title text-white bg-dark mb-3" style="text-align: center;">${response.fields.date}</h6>
              </div>
              </div>
              </div>`
              
              $('#todolist').append(card);
              $('#title').val('')
              $('#description').val('')
            }
          })
        }
      })

      deleteTask = (taskId) => {
        $.ajax({
          url: `/todolist/delete/${taskId}`,
          type: 'DELETE',
          success: function(response){
            $(`#${taskId}--task`).remove()
          }
        })
      }
    });
  </script>
</head>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid navbar-dark bg-dark">
        <a class="navbar-brand navbar-dark bg-dark">Hello, {{username}}!</a>
        <button class="navbar-toggler navbar-dark bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon navbar-dark bg-dark"></span>
          </button>
          <div class="collapse navbar-collapse navbar-dark bg-dark" id="navbarSupportedContent">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link navbar-dark bg-dark cursor-pointer" data-bs-toggle="modal" data-bs-target="#createTaskModal">Add Task<span class="sr-only navbar-dark bg-dark"></span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link navbar-dark bg-dark" href="{% url 'todolist:logout' %}">Logout</a>
                </li>
              </ul>
          </div>
    </div>
  </nav>

<div class="modal fade" id="createTaskModal" tabindex="-1" role="dialog" aria-labelledby="createTaskModalLabel" aria-hidden="true">
  <div class="modal-dialog bg-dark" role="document">
    <div class="modal-content bg-dark">
      <div class="modal-header">
        <h5 class="modal-title text-white" id="createTaskModalLabel">Add Task</h5>
      </div>
      <div class="modal-body">
        {% csrf_token %}
        <label class="text-white font-bold">Title</label>
        <input id="title" class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-zinc-800 mb-3 leading-tight focus:outline-none focus:shadow-outline" type="title" name="title" placeholder="Task Title">
        <label class="text-white font-bold">Description</label>
        <input id="description" class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-zinc-800 mb-3 leading-tight focus:outline-none focus:shadow-outline" type="description" name="description" placeholder="Task Description">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button id="add-task" type="button" class="btn btn-primary" data-bs-dismiss="modal">Add task</button>
      </div>
    </div>
  </div>
</div>

<h1 class="text-zinc-800" style="font-weight:bold ; font-size:50px; margin-bottom: 20px; text-align: center;">Todolist</h1>

<div class="items-center flex justify-center">
  <div class="grid gap-4 grid-cols-1 sm:grid-flow-cols-1 md:grid-cols-3 lg:grid-cols-4 m-4" id="todolist"></div>
</div>

<h5 class="text-zinc-800" style="text-align: center; margin-top:0px">Sesi terakhir login: {{ last_login }}</h5>


{% endblock content %}